version: '2'
services:
  web:
    build: .
    command: foreman start
    ports:
        - "3000:3000"
        - "3001:3001"
    volumes:
      -  .:/app
    environment:
      RAILS_ENV: development
